version: 1.0.{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: X/mMM/3eo9aFK7x5nlg3k50leOMaum6vKGxskGzniWXQ7+pMsbrus0q1tCwCAePo

build_script:
- ps: .\build.ps1

after_build:
- cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover result.xml
